# Generated by Django 3.1.3 on 2020-11-15 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_auto_20201115_1824'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='confirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='company',
            name='status',
            field=models.IntegerField(choices=[(0, 'active'), (1, 'inactive')], default=1),
        ),
    ]
