# Generated by Django 3.0.6 on 2020-11-15 17:24

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Countries',
                'db_table': 'Countries',
            },
        ),
        migrations.CreateModel(
            name='DialingCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=3, unique=True, validators=[django.core.validators.RegexValidator('^\\d+$'), django.core.validators.MinLengthValidator(2)])),
            ],
            options={
                'db_table': 'DialingCodes',
            },
        ),
        migrations.CreateModel(
            name='Industry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, unique=True)),
                ('parent_industry', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_industries', to='general.Industry')),
            ],
            options={
                'verbose_name_plural': 'Industries',
                'db_table': 'Industries',
            },
        ),
    ]
