PKD_OPTIONS = [
    (
        "PKD 01.11.Z",
        "Uprawa zbóż, roślin strączkowych i roślin oleistych na nasiona, z wyłączeniem ryżu",
    ),
    ("PKD 01.12.Z", "Uprawa ryżu"),
    (
        "PKD 01.13.Z",
        "Uprawa warzyw, włączając melony oraz uprawa roślin korzeniowych i roślin bulwiastych",
    ),
    ("PKD 01.14.Z", "Uprawa trzciny cukrowej"),
    ("PKD 01.15.Z", "Uprawa tytoniu"),
    ("PKD 01.16.Z", "Uprawa roślin włóknistych"),
    ("PKD 01.19.Z", "Pozostałe uprawy rolne inne niż wieloletnie"),
    ("PKD 01.21.Z", "Uprawa winogron"),
    ("PKD 01.22.Z", "Uprawa drzew i krzewów owocowych tropikalnych i podzwrotnikowych"),
    ("PKD 01.23.Z", "Uprawa drzew i krzewów owocowych cytrusowych"),
    ("PKD 01.24.Z", "Uprawa drzew i krzewów owocowych ziarnkowych i pestkowych"),
    ("PKD 01.25.Z", "Uprawa pozostałych drzew i krzewów owocowych oraz orzechów"),
    ("PKD 01.26.Z", "Uprawa drzew oleistych"),
    ("PKD 01.27.Z", "Uprawa roślin wykorzystywanych do produkcji napojów"),
    (
        "PKD 01.28.Z",
        "Uprawa roślin przyprawowych i aromatycznych oraz roślin wykorzystywanych do produkcji leków i wyrobów farmaceutycznych",
    ),
    ("PKD 01.29.Z", "Uprawa pozostałych roślin wieloletnich"),
    ("PKD 01.30.Z", "Rozmnażanie roślin"),
    ("PKD 01.41.Z", "Chów i hodowla bydła mlecznego"),
    ("PKD 01.42.Z", "Chów i hodowla pozostałego bydła i bawołów"),
    ("PKD 01.43.Z", "Chów i hodowla koni i pozostałych zwierząt koniowatych"),
    ("PKD 01.44.Z", "Chów i hodowla wielbłądów i zwierząt wielbłądowatych"),
    ("PKD 01.45.Z", "Chów i hodowla owiec i kóz"),
    ("PKD 01.46.Z", "Chów i hodowla świń"),
    ("PKD 01.47.Z", "Chów i hodowla drobiu"),
    ("PKD 01.49.Z", "Chów i hodowla pozostałych zwierząt"),
    (
        "PKD 01.50.Z",
        "Uprawy rolne połączone z chowem i hodowlą zwierząt (działalność mieszana)",
    ),
    ("PKD 01.61.Z", "Działalność usługowa wspomagająca produkcję roślinną"),
    (
        "PKD 01.62.Z",
        "Działalność usługowa wspomagająca chów i hodowlę zwierząt gospodarskich",
    ),
    ("PKD 01.63.Z", "Działalność usługowa następująca po zbiorach"),
    ("PKD 01.64.Z", "Obróbka nasion dla celów rozmnażania roślin"),
    (
        "PKD 01.70.Z",
        "Łowiectwo i pozyskiwanie zwierząt łownych, włączając działalność usługową",
    ),
    (
        "PKD 02.10.Z",
        "Gospodarka leśna i pozostała działalność leśna, z wyłączeniem pozyskiwania produktów leśnych",
    ),
    ("PKD 02.20.Z", "Pozyskiwanie drewna"),
    (
        "PKD 02.30.Z",
        "Pozyskiwanie dziko rosnących produktów leśnych, z wyłączeniem drewna",
    ),
    ("PKD 02.40.Z", "Działalność usługowa związana z leśnictwem"),
    ("PKD 03.11.Z", "Rybołówstwo w wodach morskich"),
    ("PKD 03.12.Z", "Rybołówstwo w wodach śródlądowych"),
    (
        "PKD 03.21.Z",
        "Chów i hodowla ryb oraz pozostałych organizmów wodnych w wodach morskich",
    ),
    (
        "PKD 03.22.Z",
        "Chów i hodowla ryb oraz pozostałych organizmów wodnych w wodach śródlądowych",
    ),
    ("PKD 05.10.Z", "Wydobywanie węgla kamiennego"),
    ("PKD 05.20.Z", "Wydobywanie węgla brunatnego (lignitu)"),
    ("PKD 06.10.Z", "Górnictwo ropy naftowej"),
    ("PKD 06.20.Z", "Górnictwo gazu ziemnego"),
    ("PKD 07.10.Z", "Górnictwo rud żelaza"),
    ("PKD 07.21.Z", "Górnictwo rud uranu i toru"),
    ("PKD 07.29.Z", "Górnictwo pozostałych rud metali nieżelaznych"),
    (
        "PKD 08.11.Z",
        "Wydobywanie kamieni ozdobnych oraz kamienia dla potrzeb budownictwa, skał wapiennych, gipsu, kredy i łupków",
    ),
    ("PKD 08.12.Z", "Wydobywanie żwiru i piasku; wydobywanie gliny i kaolinu"),
    (
        "PKD 08.91.Z",
        "Wydobywanie minerałów dla przemysłu chemicznego oraz do produkcji nawozów",
    ),
    ("PKD 08.92.Z", "Wydobywanie torfu"),
    ("PKD 08.93.Z", "Wydobywanie soli"),
    (
        "PKD 08.99.Z",
        "Pozostałe górnictwo i wydobywanie, gdzie indziej niesklasyfikowane",
    ),
    (
        "PKD 09.10.Z",
        "Działalność usługowa wspomagająca eksploatację złóż ropy naftowej i gazu ziemnego",
    ),
    (
        "PKD 09.90.Z",
        "Działalność usługowa wspomagająca pozostałe górnictwo i wydobywanie",
    ),
    (
        "PKD 10.11.Z",
        "Przetwarzanie i konserwowanie mięsa, z wyłączeniem mięsa z drobiu",
    ),
    ("PKD 10.12.Z", "Przetwarzanie i konserwowanie mięsa z drobiu"),
    ("PKD 10.13.Z", "Produkcja wyrobów z mięsa, włączając wyroby z mięsa drobiowego"),
    ("PKD 10.20.Z", "Przetwarzanie i konserwowanie ryb, skorupiaków i mięczaków"),
    ("PKD 10.31.Z", "Przetwarzanie i konserwowanie ziemniaków"),
    ("PKD 10.32.Z", "Produkcja soków z owoców i warzyw"),
    ("PKD 10.39.Z", "Pozostałe przetwarzanie i konserwowanie owoców i warzyw"),
    ("PKD 10.41.Z", "Produkcja olejów i pozostałych tłuszczów płynnych"),
    ("PKD 10.42.Z", "Produkcja margaryny i podobnych tłuszczów jadalnych"),
    ("PKD 10.51.Z", "Przetwórstwo mleka i wyrób serów"),
    ("PKD 10.52.Z", "Produkcja lodów"),
    ("PKD 10.61.Z", "Wytwarzanie produktów przemiału zbóż"),
    ("PKD 10.62.Z", "Wytwarzanie skrobi i wyrobów skrobiowych"),
    (
        "PKD 10.71.Z",
        "Produkcja pieczywa; produkcja świeżych wyrobów ciastkarskich i ciastek",
    ),
    (
        "PKD 10.72.Z",
        "Produkcja sucharów i herbatników; produkcja konserwowanych wyrobów ciastkarskich i ciastek",
    ),
    (
        "PKD 10.73.Z",
        "Produkcja makaronów, klusek, kuskusu i podobnych wyrobów mącznych",
    ),
    ("PKD 10.81.Z", "Produkcja cukru"),
    ("PKD 10.82.Z", "Produkcja kakao, czekolady i wyrobów cukierniczych"),
    ("PKD 10.83.Z", "Przetwórstwo herbaty i kawy"),
    ("PKD 10.84.Z", "Produkcja przypraw"),
    ("PKD 10.85.Z", "Wytwarzanie gotowych posiłków i dań"),
    (
        "PKD 10.86.Z",
        "Produkcja artykułów spożywczych homogenizowanych i żywności dietetycznej",
    ),
    (
        "PKD 10.89.Z",
        "Produkcja pozostałych artykułów spożywczych, gdzie indziej niesklasyfikowana",
    ),
    ("PKD 10.91.Z", "Produkcja gotowej paszy dla zwierząt gospodarskich"),
    ("PKD 10.92.Z", "Produkcja gotowej karmy dla zwierząt domowych"),
    ("PKD 11.01.Z", "Destylowanie, rektyfikowanie i mieszanie alkoholi"),
    ("PKD 11.02.Z", "Produkcja win gronowych"),
    ("PKD 11.03.Z", "Produkcja cydru i pozostałych win owocowych"),
    ("PKD 11.04.Z", "Produkcja pozostałych niedestylowanych napojów fermentowanych"),
    ("PKD 11.05.Z", "Produkcja piwa"),
    ("PKD 11.06.Z", "Produkcja słodu"),
    (
        "PKD 11.07.Z",
        "Produkcja napojów bezalkoholowych; produkcja wód mineralnych i pozostałych wód butelkowanych",
    ),
    ("PKD 12.00.Z", "PRODUKCJA WYROBÓW TYTONIOWYCH"),
    ("PKD 13.10.A", "Produkcja przędzy bawełnianej"),
    ("PKD 13.10.B", "Produkcja przędzy wełnianej"),
    ("PKD 13.10.C", "Produkcja przędzy z włókien chemicznych"),
    (
        "PKD 13.10.D",
        "Produkcja przędzy z pozostałych włókien tekstylnych, włączając produkcję nici",
    ),
    ("PKD 13.20.A", "Produkcja tkanin bawełnianych"),
    ("PKD 13.20.B", "Produkcja tkanin wełnianych"),
    ("PKD 13.20.C", "Produkcja tkanin z włókien chemicznych"),
    ("PKD 13.20.D", "Produkcja pozostałych tkanin"),
    ("PKD 13.30.Z", "Wykończanie wyrobów włókienniczych"),
    ("PKD 13.91.Z", "Produkcja dzianin metrażowych"),
    ("PKD 13.92.Z", "Produkcja gotowych wyrobów tekstylnych"),
    ("PKD 13.93.Z", "Produkcja dywanów i chodników"),
    (
        "PKD 13.94.Z",
        "Produkcja wyrobów powroźniczych, lin, szpagatów i wyrobów sieciowych",
    ),
    (
        "PKD 13.95.Z",
        "Produkcja włóknin i wyrobów wykonanych z włóknin, z wyłączeniem odzieży",
    ),
    (
        "PKD 13.96.Z",
        "Produkcja pozostałych technicznych i przemysłowych wyrobów tekstylnych",
    ),
    (
        "PKD 13.99.Z",
        "Produkcja pozostałych wyrobów tekstylnych, gdzie indziej niesklasyfikowana",
    ),
    ("PKD 14.11.Z", "Produkcja odzieży skórzanej"),
    ("PKD 14.12.Z", "Produkcja odzieży roboczej"),
    ("PKD 14.13.Z", "Produkcja pozostałej odzieży wierzchniej"),
    ("PKD 14.14.Z", "Produkcja bielizny"),
    ("PKD 14.19.Z", "Produkcja pozostałej odzieży i dodatków do odzieży"),
    ("PKD 14.20.Z", "Produkcja wyrobów futrzarskich"),
    ("PKD 14.31.Z", "Produkcja wyrobów pończoszniczych"),
    ("PKD 14.39.Z", "Produkcja pozostałej odzieży dzianej"),
    ("PKD 15.11.Z", "Wyprawa skór, garbowanie; wyprawa i barwienie skór futerkowych"),
    (
        "PKD 15.12.Z",
        "Produkcja toreb bagażowych, toreb ręcznych i podobnych wyrobów kaletniczych; produkcja wyrobów rymarskich",
    ),
    ("PKD 15.20.Z", "Produkcja obuwia"),
    ("PKD 16.10.Z", "Produkcja wyrobów tartacznych"),
    ("PKD 16.21.Z", "Produkcja arkuszy fornirowych i płyt wykonanych na bazie drewna"),
    ("PKD 16.22.Z", "Produkcja gotowych parkietów podłogowych"),
    (
        "PKD 16.23.Z",
        "Produkcja pozostałych wyrobów stolarskich i ciesielskich dla budownictwa",
    ),
    ("PKD 16.24.Z", "Produkcja opakowań drewnianych"),
    (
        "PKD 16.29.Z",
        "Produkcja pozostałych wyrobów z drewna; produkcja wyrobów z korka, słomy i materiałów używanych do wyplatania",
    ),
    ("PKD 17.11.Z", "Produkcja masy włóknistej"),
    ("PKD 17.12.Z", "Produkcja papieru i tektury"),
    (
        "PKD 17.21.Z",
        "Produkcja papieru falistego i tektury falistej oraz opakowań z papieru i tektury",
    ),
    (
        "PKD 17.22.Z",
        "Produkcja artykułów gospodarstwa domowego, toaletowych i sanitarnych",
    ),
    ("PKD 17.23.Z", "Produkcja artykułów piśmiennych"),
    ("PKD 17.24.Z", "Produkcja tapet"),
    ("PKD 17.29.Z", "Produkcja pozostałych wyrobów z papieru i tektury"),
    ("PKD 18.11.Z", "Drukowanie gazet"),
    ("PKD 18.12.Z", "Pozostałe drukowanie"),
    ("PKD 18.13.Z", "Działalność usługowa związana z przygotowywaniem do druku"),
    ("PKD 18.14.Z", "Introligatorstwo i podobne usługi"),
    ("PKD 18.20.Z", "Reprodukcja zapisanych nośników informacji"),
    ("PKD 19.10.Z", "Wytwarzanie i przetwarzanie koksu"),
    ("PKD 19.20.Z", "Wytwarzanie i przetwarzanie produktów rafinacji ropy naftowej"),
    ("PKD 20.11.Z", "Produkcja gazów technicznych"),
    ("PKD 20.12.Z", "Produkcja barwników i pigmentów"),
    ("PKD 20.13.Z", "Produkcja pozostałych podstawowych chemikaliów nieorganicznych"),
    ("PKD 20.14.Z", "Produkcja pozostałych podstawowych chemikaliów organicznych"),
    ("PKD 20.15.Z", "Produkcja nawozów i związków azotowych"),
    ("PKD 20.16.Z", "Produkcja tworzyw sztucznych w formach podstawowych"),
    ("PKD 20.17.Z", "Produkcja kauczuku syntetycznego w formach podstawowych"),
    ("PKD 20.20.Z", "Produkcja pestycydów i pozostałych środków agrochemicznych"),
    (
        "PKD 20.30.Z",
        "Produkcja farb, lakierów i podobnych powłok, farb drukarskich i mas uszczelniających",
    ),
    ("PKD 20.41.Z", "Produkcja mydła i detergentów, środków myjących i czyszczących"),
    ("PKD 20.42.Z", "Produkcja wyrobów kosmetycznych i toaletowych"),
    ("PKD 20.51.Z", "Produkcja materiałów wybuchowych"),
    ("PKD 20.52.Z", "Produkcja klejów"),
    ("PKD 20.53.Z", "Produkcja olejków eterycznych"),
    (
        "PKD 20.59.Z",
        "Produkcja pozostałych wyrobów chemicznych, gdzie indziej niesklasyfikowana",
    ),
    ("PKD 20.60.Z", "Produkcja włókien chemicznych"),
    ("PKD 21.10.Z", "Produkcja podstawowych substancji farmaceutycznych"),
    ("PKD 21.20.Z", "Produkcja leków i pozostałych wyrobów farmaceutycznych"),
    (
        "PKD 22.11.Z",
        "Produkcja opon i dętek z gumy; bieżnikowanie i regenerowanie opon z gumy",
    ),
    ("PKD 22.19.Z", "Produkcja pozostałych wyrobów z gumy"),
    (
        "PKD 22.21.Z",
        "Produkcja płyt, arkuszy, rur i kształtowników z tworzyw sztucznych",
    ),
    ("PKD 22.22.Z", "Produkcja opakowań z tworzyw sztucznych"),
    ("PKD 22.23.Z", "Produkcja wyrobów dla budownictwa z tworzyw sztucznych"),
    ("PKD 22.29.Z", "Produkcja pozostałych wyrobów z tworzyw sztucznych"),
    ("PKD 23.11.Z", "Produkcja szkła płaskiego"),
    ("PKD 23.12.Z", "Kształtowanie i obróbka szkła płaskiego"),
    ("PKD 23.13.Z", "Produkcja szkła gospodarczego"),
    ("PKD 23.14.Z", "Produkcja włókien szklanych"),
    (
        "PKD 23.19.Z",
        "Produkcja i obróbka pozostałego szkła, włączając szkło techniczne",
    ),
    ("PKD 23.20.Z", "Produkcja wyrobów ogniotrwałych"),
    ("PKD 23.31.Z", "Produkcja ceramicznych kafli i płytek"),
    (
        "PKD 23.32.Z",
        "Produkcja cegieł, dachówek i materiałów budowlanych, z wypalanej gliny",
    ),
    ("PKD 23.41.Z", "Produkcja ceramicznych wyrobów stołowych i ozdobnych"),
    ("PKD 23.42.Z", "Produkcja ceramicznych wyrobów sanitarnych"),
    ("PKD 23.43.Z", "Produkcja ceramicznych izolatorów i osłon izolacyjnych"),
    ("PKD 23.44.Z", "Produkcja pozostałych technicznych wyrobów ceramicznych"),
    ("PKD 23.49.Z", "Produkcja pozostałych wyrobów ceramicznych"),
    ("PKD 23.51.Z", "Produkcja cementu"),
    ("PKD 23.52.Z", "Produkcja wapna i gipsu"),
    ("PKD 23.61.Z", "Produkcja wyrobów budowlanych z betonu"),
    ("PKD 23.62.Z", "Produkcja wyrobów budowlanych z gipsu"),
    ("PKD 23.63.Z", "Produkcja masy betonowej prefabrykowanej"),
    ("PKD 23.64.Z", "Produkcja zaprawy murarskiej"),
    ("PKD 23.65.Z", "Produkcja cementu wzmocnionego włóknem"),
    ("PKD 23.69.Z", "Produkcja pozostałych wyrobów z betonu, gipsu i cementu"),
    ("PKD 23.70.Z", "Cięcie, formowanie i wykańczanie kamienia"),
    ("PKD 23.91.Z", "Produkcja wyrobów ściernych"),
    (
        "PKD 23.99.Z",
        "Produkcja pozostałych wyrobów z mineralnych surowców niemetalicznych, gdzie indziej niesklasyfikowana",
    ),
    (
        "PKD 24.10.Z",
        "Produkcja surówki, żelazostopów, żeliwa i stali oraz wyrobów hutniczych",
    ),
    (
        "PKD 24.20.Z",
        "Produkcja rur, przewodów, kształtowników zamkniętych i łączników, ze stali",
    ),
    ("PKD 24.31.Z", "Produkcja prętów ciągnionych na zimno"),
    ("PKD 24.32.Z", "Produkcja wyrobów płaskich walcowanych na zimno"),
    ("PKD 24.33.Z", "Produkcja wyrobów formowanych na zimno"),
    ("PKD 24.34.Z", "Produkcja drutu"),
    ("PKD 24.41.Z", "Produkcja metali szlachetnych"),
    ("PKD 24.42.A", "Produkcja aluminium hutniczego"),
    ("PKD 24.42.B", "Produkcja wyrobów z aluminium i stopów aluminium"),
    ("PKD 24.43.Z", "Produkcja ołowiu, cynku i cyny"),
    ("PKD 24.44.Z", "Produkcja miedzi"),
    ("PKD 24.45.Z", "Produkcja pozostałych metali nieżelaznych"),
    ("PKD 24.46.Z", "Wytwarzanie paliw jądrowych"),
    ("PKD 24.51.Z", "Odlewnictwo żeliwa"),
    ("PKD 24.52.Z", "Odlewnictwo staliwa"),
    ("PKD 24.53.Z", "Odlewnictwo metali lekkich"),
    ("PKD 24.54.A", "Odlewnictwo miedzi i stopów miedzi"),
    (
        "PKD 24.54.B",
        "Odlewnictwo pozostałych metali nieżelaznych, gdzie indziej niesklasyfikowane",
    ),
    ("PKD 25.11.Z", "Produkcja konstrukcji metalowych i ich części"),
    ("PKD 25.12.Z", "Produkcja metalowych elementów stolarki budowlanej"),
    ("PKD 25.21.Z", "Produkcja grzejników i kotłów centralnego ogrzewania"),
    (
        "PKD 25.29.Z",
        "Produkcja pozostałych zbiorników, cystern i pojemników metalowych",
    ),
    (
        "PKD 25.30.Z",
        "Produkcja wytwornic pary, z wyłączeniem kotłów do centralnego ogrzewania gorącą wodą",
    ),
    ("PKD 25.40.Z", "Produkcja broni i amunicji"),
    (
        "PKD 25.50.Z",
        "Kucie, prasowanie, wytłaczanie i walcowanie metali; metalurgia proszków",
    ),
    ("PKD 25.61.Z", "Obróbka metali i nakładanie powłok na metale"),
    ("PKD 25.62.Z", "Obróbka mechaniczna elementów metalowych"),
    ("PKD 25.71.Z", "Produkcja wyrobów nożowniczych i sztućców"),
    ("PKD 25.72.Z", "Produkcja zamków i zawiasów"),
    ("PKD 25.73.Z", "Produkcja narzędzi"),
    ("PKD 25.91.Z", "Produkcja pojemników metalowych"),
    ("PKD 25.92.Z", "Produkcja opakowań z metali"),
    ("PKD 25.93.Z", "Produkcja wyrobów z drutu, łańcuchów i sprężyn"),
    ("PKD 25.94.Z", "Produkcja złączy i śrub"),
    (
        "PKD 25.99.Z",
        "Produkcja pozostałych gotowych wyrobów metalowych, gdzie indziej niesklasyfikowana",
    ),
    ("PKD 26.11.Z", "Produkcja elementów elektronicznych"),
    ("PKD 26.12.Z", "Produkcja elektronicznych obwodów drukowanych"),
    ("PKD 26.20.Z", "Produkcja komputerów i urządzeń peryferyjnych"),
    ("PKD 26.30.Z", "Produkcja sprzętu (tele)komunikacyjnego"),
    ("PKD 26.40.Z", "Produkcja elektronicznego sprzętu powszechnego użytku"),
    (
        "PKD 26.51.Z",
        "Produkcja instrumentów i przyrządów pomiarowych, kontrolnych i nawigacyjnych",
    ),
    ("PKD 26.52.Z", "Produkcja zegarków i zegarów"),
    (
        "PKD 26.60.Z",
        "Produkcja urządzeń napromieniowujących, sprzętu elektromedycznego i elektroterapeutycznego",
    ),
    ("PKD 26.70.Z", "Produkcja instrumentów optycznych i sprzętu fotograficznego"),
    (
        "PKD 26.80.Z",
        "Produkcja magnetycznych i optycznych niezapisanych nośników informacji",
    ),
    ("PKD 27.11.Z", "Produkcja elektrycznych silników, prądnic i transformatorów"),
    (
        "PKD 27.12.Z",
        "Produkcja aparatury rozdzielczej i sterowniczej energii elektrycznej",
    ),
    ("PKD 27.20.Z", "Produkcja baterii i akumulatorów"),
    ("PKD 27.31.Z", "Produkcja kabli światłowodowych"),
    (
        "PKD 27.32.Z",
        "Produkcja pozostałych elektronicznych i elektrycznych przewodów i kabli",
    ),
    ("PKD 27.33.Z", "Produkcja sprzętu instalacyjnego"),
    ("PKD 27.40.Z", "Produkcja elektrycznego sprzętu oświetleniowego"),
    ("PKD 27.51.Z", "Produkcja elektrycznego sprzętu gospodarstwa domowego"),
    ("PKD 27.52.Z", "Produkcja nieelektrycznego sprzętu gospodarstwa domowego"),
    ("PKD 27.90.Z", "Produkcja pozostałego sprzętu elektrycznego"),
    (
        "PKD 28.11.Z",
        "Produkcja silników i turbin, z wyłączeniem silników lotniczych, samochodowych i motocyklowych",
    ),
    (
        "PKD 28.12.Z",
        "Produkcja sprzętu i wyposażenia do napędu hydraulicznego i pneumatycznego",
    ),
    ("PKD 28.13.Z", "Produkcja pozostałych pomp i sprężarek"),
    ("PKD 28.14.Z", "Produkcja pozostałych kurków i zaworów"),
    (
        "PKD 28.15.Z",
        "Produkcja łożysk, kół zębatych, przekładni zębatych i elementów napędowych",
    ),
    ("PKD 28.21.Z", "Produkcja pieców, palenisk i palników piecowych"),
    ("PKD 28.22.Z", "Produkcja urządzeń dźwigowych i chwytaków"),
    (
        "PKD 28.23.Z",
        "Produkcja maszyn i sprzętu biurowego, z wyłączeniem komputerów i urządzeń peryferyjnych",
    ),
    ("PKD 28.24.Z", "Produkcja narzędzi ręcznych mechanicznych"),
    ("PKD 28.25.Z", "Produkcja przemysłowych urządzeń chłodniczych i wentylacyjnych"),
    (
        "PKD 28.29.Z",
        "Produkcja pozostałych maszyn ogólnego przeznaczenia, gdzie indziej niesklasyfikowana",
    ),
    ("PKD 28.30.Z", "Produkcja maszyn dla rolnictwa i leśnictwa"),
    ("PKD 28.41.Z", "Produkcja maszyn do obróbki metalu"),
    ("PKD 28.49.Z", "Produkcja pozostałych narzędzi mechanicznych"),
    ("PKD 28.91.Z", "Produkcja maszyn dla metalurgii"),
    ("PKD 28.92.Z", "Produkcja maszyn dla górnictwa i do wydobywania oraz budownictwa"),
    (
        "PKD 28.93.Z",
        "Produkcja maszyn stosowanych w przetwórstwie żywności, tytoniu i produkcji napojów",
    ),
    (
        "PKD 28.94.Z",
        "Produkcja maszyn dla przemysłu tekstylnego, odzieżowego i skórzanego",
    ),
    ("PKD 28.95.Z", "Produkcja maszyn dla przemysłu papierniczego"),
    (
        "PKD 28.96.Z",
        "Produkcja maszyn do obróbki gumy lub tworzyw sztucznych oraz wytwarzania wyrobów z tych materiałów",
    ),
    (
        "PKD 28.99.Z",
        "Produkcja pozostałych maszyn specjalnego przeznaczenia, gdzie indziej niesklasyfikowana",
    ),
    (
        "PKD 29.10.A",
        "Produkcja silników do pojazdów samochodowych (z wyłączeniem motocykli) oraz do ciągników rolniczych",
    ),
    ("PKD 29.10.B", "Produkcja samochodów osobowych"),
    ("PKD 29.10.C", "Produkcja autobusów"),
    (
        "PKD 29.10.D",
        "Produkcja pojazdów samochodowych przeznaczonych do przewozu towarów",
    ),
    (
        "PKD 29.10.E",
        "Produkcja pozostałych pojazdów samochodowych, z wyłączeniem motocykli",
    ),
    (
        "PKD 29.20.Z",
        "Produkcja nadwozi do pojazdów silnikowych; produkcja przyczep i naczep",
    ),
    (
        "PKD 29.31.Z",
        "Produkcja wyposażenia elektrycznego i elektronicznego do pojazdów silnikowych",
    ),
    (
        "PKD 29.32.Z",
        "Produkcja pozostałych części i akcesoriów do pojazdów silnikowych, z wyłączeniem motocykli",
    ),
    ("PKD 30.11.Z", "Produkcja statków i konstrukcji pływających"),
    ("PKD 30.12.Z", "Produkcja łodzi wycieczkowych i sportowych"),
    ("PKD 30.20.Z", "Produkcja lokomotyw kolejowych oraz taboru szynowego"),
    (
        "PKD 30.30.Z",
        "Produkcja statków powietrznych, statków kosmicznych i podobnych maszyn",
    ),
    ("PKD 30.40.Z", "Produkcja wojskowych pojazdów bojowych"),
    ("PKD 30.91.Z", "Produkcja motocykli"),
    ("PKD 30.92.Z", "Produkcja rowerów i wózków inwalidzkich"),
    (
        "PKD 30.99.Z",
        "Produkcja pozostałego sprzętu transportowego, gdzie indziej niesklasyfikowana",
    ),
    ("PKD 31.01.Z", "Produkcja mebli biurowych i sklepowych"),
    ("PKD 31.02.Z", "Produkcja mebli kuchennych"),
    ("PKD 31.03.Z", "Produkcja materaców"),
    ("PKD 31.09.Z", "Produkcja pozostałych mebli"),
    ("PKD 32.11.Z", "Produkcja monet"),
    ("PKD 32.12.Z", "Produkcja wyrobów jubilerskich i podobnych"),
    ("PKD 32.13.Z", "Produkcja sztucznej biżuterii i wyrobów podobnych"),
    ("PKD 32.20.Z", "Produkcja instrumentów muzycznych"),
    ("PKD 32.30.Z", "Produkcja sprzętu sportowego"),
    ("PKD 32.40.Z", "Produkcja gier i zabawek"),
    (
        "PKD 32.50.Z",
        "Produkcja urządzeń, instrumentów oraz wyrobów medycznych, włączając dentystyczne",
    ),
    ("PKD 32.91.Z", "Produkcja mioteł, szczotek i pędzli"),
    ("PKD 32.99.Z", "Produkcja pozostałych wyrobów, gdzie indziej niesklasyfikowana"),
    ("PKD 33.11.Z", "Naprawa i konserwacja metalowych wyrobów gotowych"),
    ("PKD 33.12.Z", "Naprawa i konserwacja maszyn"),
    ("PKD 33.13.Z", "Naprawa i konserwacja urządzeń elektronicznych i optycznych"),
    ("PKD 33.14.Z", "Naprawa i konserwacja urządzeń elektrycznych"),
    ("PKD 33.15.Z", "Naprawa i konserwacja statków i łodzi"),
    ("PKD 33.16.Z", "Naprawa i konserwacja statków powietrznych i statków kosmicznych"),
    ("PKD 33.17.Z", "Naprawa i konserwacja pozostałego sprzętu transportowego"),
    ("PKD 33.19.Z", "Naprawa i konserwacja pozostałego sprzętu i wyposażenia"),
    ("PKD 33.20.Z", "Instalowanie maszyn przemysłowych, sprzętu i wyposażenia"),
    ("PKD 35.11.Z", "Wytwarzanie energii elektrycznej"),
    ("PKD 35.12.Z", "Przesyłanie energii elektrycznej"),
    ("PKD 35.13.Z", "Dystrybucja energii elektrycznej"),
    ("PKD 35.14.Z", "Handel energią elektryczną"),
    ("PKD 35.21.Z", "Wytwarzanie paliw gazowych"),
    ("PKD 35.22.Z", "Dystrybucja paliw gazowych w systemie sieciowym"),
    ("PKD 35.23.Z", "Handel paliwami gazowymi w systemie sieciowym"),
    (
        "PKD 35.30.Z",
        "Wytwarzanie i zaopatrywanie w parę wodną, gorącą wodę i powietrze do układów klimatyzacyjnych",
    ),
    ("PKD 36.00.Z", "POBÓR, UZDATNIANIE I DOSTARCZANIE WODY"),
    ("PKD 37.00.Z", "ODPROWADZANIE I OCZYSZCZANIE ŚCIEKÓW"),
    ("PKD 38.11.Z", "Zbieranie odpadów innych niż niebezpieczne"),
    ("PKD 38.12.Z", "Zbieranie odpadów niebezpiecznych"),
    ("PKD 38.21.Z", "Obróbka i usuwanie odpadów innych niż niebezpieczne"),
    ("PKD 38.22.Z", "Przetwarzanie i unieszkodliwianie odpadów niebezpiecznych"),
    ("PKD 38.31.Z", "Demontaż wyrobów zużytych"),
    ("PKD 38.32.Z", "Odzysk surowców z materiałów segregowanych"),
    (
        "PKD 39.00.Z",
        "DZIAŁALNOŚĆ ZWIĄZANA Z REKULTYWACJĄ I POZOSTAŁA DZIAŁALNOŚĆ USŁUGOWA ZWIĄZANA Z GOSPODARKĄ ODPADAMI",
    ),
    (
        "PKD 41.10.Z",
        "Realizacja projektów budowlanych związanych ze wznoszeniem budynków",
    ),
    (
        "PKD 41.20.Z",
        "Roboty budowlane związane ze wznoszeniem budynków mieszkalnych i niemieszkalnych",
    ),
    ("PKD 42.11.Z", "Roboty związane z budową dróg i autostrad"),
    ("PKD 42.12.Z", "Roboty związane z budową dróg szynowych i kolei podziemnej"),
    ("PKD 42.13.Z", "Roboty związane z budową mostów i tuneli"),
    (
        "PKD 42.21.Z",
        "Roboty związane z budową rurociągów przesyłowych i sieci rozdzielczych",
    ),
    (
        "PKD 42.22.Z",
        "Roboty związane z budową linii telekomunikacyjnych i elektroenergetycznych",
    ),
    ("PKD 42.91.Z", "Roboty związane z budową obiektów inżynierii wodnej"),
    (
        "PKD 42.99.Z",
        "Roboty związane z budową pozostałych obiektów inżynierii lądowej i wodnej, gdzie indziej niesklasyfikowane",
    ),
    ("PKD 43.11.Z", "Rozbiórka i burzenie obiektów budowlanych"),
    ("PKD 43.12.Z", "Przygotowanie terenu pod budowę"),
    ("PKD 43.13.Z", "Wykonywanie wykopów i wierceń geologiczno-inżynierskich"),
    ("PKD 43.21.Z", "Wykonywanie instalacji elektrycznych"),
    (
        "PKD 43.22.Z",
        "Wykonywanie instalacji wodno-kanalizacyjnych, cieplnych, gazowych i klimatyzacyjnych",
    ),
    ("PKD 43.29.Z", "Wykonywanie pozostałych instalacji budowlanych"),
    ("PKD 43.31.Z", "Tynkowanie"),
    ("PKD 43.32.Z", "Zakładanie stolarki budowlanej"),
    ("PKD 43.33.Z", "Posadzkarstwo; tapetowanie i oblicowywanie ścian"),
    ("PKD 43.34.Z", "Malowanie i szklenie"),
    ("PKD 43.39.Z", "Wykonywanie pozostałych robót budowlanych wykończeniowych"),
    ("PKD 43.91.Z", "Wykonywanie konstrukcji i pokryć dachowych"),
    (
        "PKD 43.99.Z",
        "Pozostałe specjalistyczne roboty budowlane, gdzie indziej niesklasyfikowane",
    ),
    ("PKD 45.11.Z", "Sprzedaż hurtowa i detaliczna samochodów osobowych i furgonetek"),
    (
        "PKD 45.19.Z",
        "Sprzedaż hurtowa i detaliczna pozostałych pojazdów samochodowych, z wyłączeniem motocykli",
    ),
    (
        "PKD 45.20.Z",
        "Konserwacja i naprawa pojazdów samochodowych, z wyłączeniem motocykli",
    ),
    (
        "PKD 45.31.Z",
        "Sprzedaż hurtowa części i akcesoriów do pojazdów samochodowych, z wyłączeniem motocykli",
    ),
    (
        "PKD 45.32.Z",
        "Sprzedaż detaliczna części i akcesoriów do pojazdów samochodowych, z wyłączeniem motocykli",
    ),
    (
        "PKD 45.40.Z",
        "Sprzedaż hurtowa i detaliczna motocykli, ich naprawa i konserwacja oraz sprzedaż hurtowa i detaliczna części i akcesoriów do nich",
    ),
    (
        "PKD 46.11.Z",
        "Działalność agentów zajmujących się sprzedażą płodów rolnych, żywych zwierząt, surowców dla przemysłu tekstylnego i półproduktów",
    ),
    (
        "PKD 46.12.Z",
        "Działalność agentów zajmujących się sprzedażą paliw, rud, metali i chemikaliów przemysłowych",
    ),
    (
        "PKD 46.13.Z",
        "Działalność agentów zajmujących się sprzedażą drewna i materiałów budowlanych",
    ),
    (
        "PKD 46.14.Z",
        "Działalność agentów zajmujących się sprzedażą maszyn, urządzeń przemysłowych, statków i samolotów",
    ),
    (
        "PKD 46.15.Z",
        "Działalność agentów zajmujących się sprzedażą mebli, artykułów gospodarstwa domowego i drobnych wyrobów metalowych",
    ),
    (
        "PKD 46.16.Z",
        "Działalność agentów zajmujących się sprzedażą wyrobów tekstylnych, odzieży, wyrobów futrzarskich, obuwia i artykułów skórzanych",
    ),
    (
        "PKD 46.17.Z",
        "Działalność agentów zajmujących się sprzedażą żywności, napojów i wyrobów tytoniowych",
    ),
    (
        "PKD 46.18.Z",
        "Działalność agentów specjalizujących się w sprzedaży pozostałych określonych towarów",
    ),
    (
        "PKD 46.19.Z",
        "Działalność agentów zajmujących się sprzedażą towarów różnego rodzaju",
    ),
    (
        "PKD 46.21.Z",
        "Sprzedaż hurtowa zboża, nieprzetworzonego tytoniu, nasion i pasz dla zwierząt",
    ),
    ("PKD 46.22.Z", "Sprzedaż hurtowa kwiatów i roślin"),
    ("PKD 46.23.Z", "Sprzedaż hurtowa żywych zwierząt"),
    ("PKD 46.24.Z", "Sprzedaż hurtowa skór"),
    ("PKD 46.31.Z", "Sprzedaż hurtowa owoców i warzyw"),
    ("PKD 46.32.Z", "Sprzedaż hurtowa mięsa i wyrobów z mięsa"),
    (
        "PKD 46.33.Z",
        "Sprzedaż hurtowa mleka, wyrobów mleczarskich, jaj, olejów i tłuszczów jadalnych",
    ),
    ("PKD 46.34.A", "Sprzedaż hurtowa napojów alkoholowych"),
    ("PKD 46.34.B", "Sprzedaż hurtowa napojów bezalkoholowych"),
    ("PKD 46.35.Z", "Sprzedaż hurtowa wyrobów tytoniowych"),
    (
        "PKD 46.36.Z",
        "Sprzedaż hurtowa cukru, czekolady, wyrobów cukierniczych i piekarskich",
    ),
    ("PKD 46.37.Z", "Sprzedaż hurtowa herbaty, kawy, kakao i przypraw"),
    (
        "PKD 46.38.Z",
        "Sprzedaż hurtowa pozostałej żywności, włączając ryby, skorupiaki i mięczaki",
    ),
    (
        "PKD 46.39.Z",
        "Sprzedaż hurtowa niewyspecjalizowana żywności, napojów i wyrobów tytoniowych",
    ),
    ("PKD 46.41.Z", "Sprzedaż hurtowa wyrobów tekstylnych"),
    ("PKD 46.42.Z", "Sprzedaż hurtowa odzieży i obuwia"),
    ("PKD 46.43.Z", "Sprzedaż hurtowa elektrycznych artykułów użytku domowego"),
    (
        "PKD 46.44.Z",
        "Sprzedaż hurtowa wyrobów porcelanowych, ceramicznych i szklanych oraz środków czyszczących",
    ),
    ("PKD 46.45.Z", "Sprzedaż hurtowa perfum i kosmetyków"),
    ("PKD 46.46.Z", "Sprzedaż hurtowa wyrobów farmaceutycznych i medycznych"),
    ("PKD 46.47.Z", "Sprzedaż hurtowa mebli, dywanów i sprzętu oświetleniowego"),
    ("PKD 46.48.Z", "Sprzedaż hurtowa zegarków, zegarów i biżuterii"),
    ("PKD 46.49.Z", "Sprzedaż hurtowa pozostałych artykułów użytku domowego"),
    (
        "PKD 46.51.Z",
        "Sprzedaż hurtowa komputerów, urządzeń peryferyjnych i oprogramowania",
    ),
    (
        "PKD 46.52.Z",
        "Sprzedaż hurtowa sprzętu elektronicznego i telekomunikacyjnego oraz części do niego",
    ),
    (
        "PKD 46.61.Z",
        "Sprzedaż hurtowa maszyn i urządzeń rolniczych oraz dodatkowego wyposażenia",
    ),
    ("PKD 46.62.Z", "Sprzedaż hurtowa obrabiarek"),
    (
        "PKD 46.63.Z",
        "Sprzedaż hurtowa maszyn wykorzystywanych w górnictwie, budownictwie oraz inżynierii lądowej i wodnej",
    ),
    (
        "PKD 46.64.Z",
        "Sprzedaż hurtowa maszyn dla przemysłu tekstylnego oraz maszyn do szycia i maszyn dziewiarskich",
    ),
    ("PKD 46.65.Z", "Sprzedaż hurtowa mebli biurowych"),
    ("PKD 46.66.Z", "Sprzedaż hurtowa pozostałych maszyn i urządzeń biurowych"),
    ("PKD 46.69.Z", "Sprzedaż hurtowa pozostałych maszyn i urządzeń"),
    ("PKD 46.71.Z", "Sprzedaż hurtowa paliw i produktów pochodnych"),
    ("PKD 46.72.Z", "Sprzedaż hurtowa metali i rud metali"),
    (
        "PKD 46.73.Z",
        "Sprzedaż hurtowa drewna, materiałów budowlanych i wyposażenia sanitarnego",
    ),
    (
        "PKD 46.74.Z",
        "Sprzedaż hurtowa wyrobów metalowych oraz sprzętu i dodatkowego wyposażenia hydraulicznego i grzejnego",
    ),
    ("PKD 46.75.Z", "Sprzedaż hurtowa wyrobów chemicznych"),
    ("PKD 46.76.Z", "Sprzedaż hurtowa pozostałych półproduktów"),
    ("PKD 46.77.Z", "Sprzedaż hurtowa odpadów i złomu"),
    ("PKD 46.90.Z", "Sprzedaż hurtowa niewyspecjalizowana"),
    (
        "PKD 47.11.Z",
        "Sprzedaż detaliczna prowadzona w niewyspecjalizowanych sklepach z przewagą żywności, napojów i wyrobów tytoniowych",
    ),
    (
        "PKD 47.19.Z",
        "Pozostała sprzedaż detaliczna prowadzona w niewyspecjalizowanych sklepach",
    ),
    (
        "PKD 47.21.Z",
        "Sprzedaż detaliczna owoców i warzyw prowadzona w wyspecjalizowanych sklepach",
    ),
    (
        "PKD 47.22.Z",
        "Sprzedaż detaliczna mięsa i wyrobów z mięsa prowadzona w wyspecjalizowanych sklepach",
    ),
    (
        "PKD 47.23.Z",
        "Sprzedaż detaliczna ryb, skorupiaków i mięczaków prowadzona w wyspecjalizowanych sklepach",
    ),
    (
        "PKD 47.24.Z",
        "Sprzedaż detaliczna pieczywa, ciast, wyrobów ciastkarskich i cukierniczych prowadzona w wyspecjalizowanych sklepach",
    ),
    (
        "PKD 47.25.Z",
        "Sprzedaż detaliczna napojów alkoholowych i bezalkoholowych prowadzona w wyspecjalizowanych sklepach",
    ),
    (
        "PKD 47.26.Z",
        "Sprzedaż detaliczna wyrobów tytoniowych prowadzona w wyspecjalizowanych sklepach",
    ),
    (
        "PKD 47.29.Z",
        "Sprzedaż detaliczna pozostałej żywności prowadzona w wyspecjalizowanych sklepach",
    ),
    (
        "PKD 47.30.Z",
        "Sprzedaż detaliczna paliw do pojazdów silnikowych na stacjach paliw",
    ),
    (
        "PKD 47.41.Z",
        "Sprzedaż detaliczna komputerów, urządzeń peryferyjnych i oprogramowania prowadzona w wyspecjalizowanych sklepach",
    ),
    (
        "PKD 47.42.Z",
        "Sprzedaż detaliczna sprzętu telekomunikacyjnego prowadzona w wyspecjalizowanych sklepach",
    ),
    (
        "PKD 47.43.Z",
        "Sprzedaż detaliczna sprzętu audiowizualnego prowadzona w wyspecjalizowanych sklepach",
    ),
    (
        "PKD 47.51.Z",
        "Sprzedaż detaliczna wyrobów tekstylnych prowadzona w wyspecjalizowanych sklepach",
    ),
    (
        "PKD 47.52.Z",
        "Sprzedaż detaliczna drobnych wyrobów metalowych, farb i szkła prowadzona w wyspecjalizowanych sklepach",
    ),
    (
        "PKD 47.53.Z",
        "Sprzedaż detaliczna dywanów, chodników i innych pokryć podłogowych oraz pokryć ściennych prowadzona w wyspecjalizowanych sklepach",
    ),
    (
        "PKD 47.54.Z",
        "Sprzedaż detaliczna elektrycznego sprzętu gospodarstwa domowego prowadzona w wyspecjalizowanych sklepach",
    ),
    (
        "PKD 47.59.Z",
        "Sprzedaż detaliczna mebli, sprzętu oświetleniowego i pozostałych artykułów użytku domowego prowadzona w wyspecjalizowanych sklepach",
    ),
    (
        "PKD 47.61.Z",
        "Sprzedaż detaliczna książek prowadzona w wyspecjalizowanych sklepach",
    ),
    (
        "PKD 47.62.Z",
        "Sprzedaż detaliczna gazet i artykułów piśmiennych prowadzona w wyspecjalizowanych sklepach",
    ),
    (
        "PKD 47.63.Z",
        "Sprzedaż detaliczna nagrań dźwiękowych i audiowizualnych prowadzona w wyspecjalizowanych sklepach",
    ),
    (
        "PKD 47.64.Z",
        "Sprzedaż detaliczna sprzętu sportowego prowadzona w wyspecjalizowanych sklepach",
    ),
    (
        "PKD 47.65.Z",
        "Sprzedaż detaliczna gier i zabawek prowadzona w wyspecjalizowanych sklepach",
    ),
    (
        "PKD 47.71.Z",
        "Sprzedaż detaliczna odzieży prowadzona w wyspecjalizowanych sklepach",
    ),
    (
        "PKD 47.72.Z",
        "Sprzedaż detaliczna obuwia i wyrobów skórzanych prowadzona w wyspecjalizowanych sklepach",
    ),
    (
        "PKD 47.73.Z",
        "Sprzedaż detaliczna wyrobów farmaceutycznych prowadzona w wyspecjalizowanych sklepach",
    ),
    (
        "PKD 47.74.Z",
        "Sprzedaż detaliczna wyrobów medycznych, włączając ortopedyczne, prowadzona w wyspecjalizowanych sklepach",
    ),
    (
        "PKD 47.75.Z",
        "Sprzedaż detaliczna kosmetyków i artykułów toaletowych prowadzona w wyspecjalizowanych sklepach",
    ),
    (
        "PKD 47.76.Z",
        "Sprzedaż detaliczna kwiatów, roślin, nasion, nawozów, żywych zwierząt domowych, karmy dla zwierząt domowych prowadzona w wyspecjalizowanych sklepach",
    ),
    (
        "PKD 47.77.Z",
        "Sprzedaż detaliczna zegarków, zegarów i biżuterii prowadzona w wyspecjalizowanych sklepach",
    ),
    (
        "PKD 47.78.Z",
        "Sprzedaż detaliczna pozostałych nowych wyrobów prowadzona w wyspecjalizowanych sklepach",
    ),
    (
        "PKD 47.79.Z",
        "Sprzedaż detaliczna artykułów używanych prowadzona w wyspecjalizowanych sklepach",
    ),
    (
        "PKD 47.81.Z",
        "Sprzedaż detaliczna żywności, napojów i wyrobów tytoniowych prowadzona na straganach i targowiskach",
    ),
    (
        "PKD 47.82.Z",
        "Sprzedaż detaliczna wyrobów tekstylnych, odzieży i obuwia prowadzona na straganach i targowiskach",
    ),
    (
        "PKD 47.89.Z",
        "Sprzedaż detaliczna pozostałych wyrobów prowadzona na straganach i targowiskach",
    ),
    (
        "PKD 47.91.Z",
        "Sprzedaż detaliczna prowadzona przez domy sprzedaży wysyłkowej lub Internet",
    ),
    (
        "PKD 47.99.Z",
        "Pozostała sprzedaż detaliczna prowadzona poza siecią sklepową, straganami i targowiskami",
    ),
    ("PKD 49.10.Z", "Transport kolejowy pasażerski międzymiastowy"),
    ("PKD 49.20.Z", "Transport kolejowy towarów"),
    ("PKD 49.31.Z", "Transport lądowy pasażerski, miejski i podmiejski"),
    ("PKD 49.32.Z", "Działalność taksówek osobowych"),
    (
        "PKD 49.39.Z",
        "Pozostały transport lądowy pasażerski, gdzie indziej niesklasyfikowany",
    ),
    ("PKD 49.41.Z", "Transport drogowy towarów"),
    ("PKD 49.42.Z", "Działalność usługowa związana z przeprowadzkami"),
    ("PKD 49.50.A", "Transport rurociągami paliw gazowych"),
    ("PKD 49.50.B", "Transport rurociągowy pozostałych towarów"),
    ("PKD 50.10.Z", "Transport morski i przybrzeżny pasażerski"),
    ("PKD 50.20.Z", "Transport morski i przybrzeżny towarów"),
    ("PKD 50.30.Z", "Transport wodny śródlądowy pasażerski"),
    ("PKD 50.40.Z", "Transport wodny śródlądowy towarów"),
    ("PKD 51.10.Z", "Transport lotniczy pasażerski"),
    ("PKD 51.21.Z", "Transport lotniczy towarów"),
    ("PKD 51.22.Z", "Transport kosmiczny"),
    ("PKD 52.10.A", "Magazynowanie i przechowywanie paliw gazowych"),
    ("PKD 52.10.B", "Magazynowanie i przechowywanie pozostałych towarów"),
    ("PKD 52.21.Z", "Działalność usługowa wspomagająca transport lądowy"),
    ("PKD 52.22.A", "Działalność usługowa wspomagająca transport morski"),
    ("PKD 52.22.B", "Działalność usługowa wspomagająca transport śródlądowy"),
    ("PKD 52.23.Z", "Działalność usługowa wspomagająca transport lotniczy"),
    ("PKD 52.24.A", "Przeładunek towarów w portach morskich"),
    ("PKD 52.24.B", "Przeładunek towarów w portach śródlądowych"),
    ("PKD 52.24.C", "Przeładunek towarów w pozostałych punktach przeładunkowych"),
    ("PKD 52.29.A", "Działalność morskich agencji transportowych"),
    ("PKD 52.29.B", "Działalność śródlądowych agencji transportowych"),
    ("PKD 52.29.C", "Działalność pozostałych agencji transportowych"),
    (
        "PKD 53.10.Z",
        "Działalność pocztowa objęta obowiązkiem świadczenia usług powszechnych (operatora publicznego)",
    ),
    ("PKD 53.20.Z", "Pozostała działalność pocztowa i kurierska"),
    ("PKD 55.10.Z", "Hotele i podobne obiekty zakwaterowania"),
    (
        "PKD 55.20.Z",
        "Obiekty noclegowe turystyczne i miejsca krótkotrwałego zakwaterowania",
    ),
    (
        "PKD 55.30.Z",
        "Pola kempingowe (włączając pola dla pojazdów kempingowych) i pola namiotowe",
    ),
    ("PKD 55.90.Z", "Pozostałe zakwaterowanie"),
    ("PKD 56.10.A", "Restauracje i inne stałe placówki gastronomiczne"),
    ("PKD 56.10.B", "Ruchome placówki gastronomiczne"),
    (
        "PKD 56.21.Z",
        "Przygotowywanie i dostarczanie żywności dla odbiorców zewnętrznych (katering)",
    ),
    ("PKD 56.29.Z", "Pozostała usługowa działalność gastronomiczna"),
    ("PKD 56.30.Z", "Przygotowywanie i podawanie napojów"),
    ("PKD 58.11.Z", "Wydawanie książek"),
    ("PKD 58.12.Z", "Wydawanie wykazów oraz list (np. adresowych, telefonicznych)"),
    ("PKD 58.13.Z", "Wydawanie gazet"),
    ("PKD 58.14.Z", "Wydawanie czasopism i pozostałych periodyków"),
    ("PKD 58.19.Z", "Pozostała działalność wydawnicza"),
    ("PKD 58.21.Z", "Działalność wydawnicza w zakresie gier komputerowych"),
    ("PKD 58.29.Z", "Działalność wydawnicza w zakresie pozostałego oprogramowania"),
    (
        "PKD 59.11.Z",
        "Działalność związana z produkcją filmów, nagrań wideo i programów telewizyjnych",
    ),
    (
        "PKD 59.12.Z",
        "Działalność postprodukcyjna związana z filmami, nagraniami wideo i programami telewizyjnymi",
    ),
    (
        "PKD 59.13.Z",
        "Działalność związana z dystrybucją filmów, nagrań wideo i programów telewizyjnych",
    ),
    ("PKD 59.14.Z", "Działalność związana z projekcją filmów"),
    ("PKD 59.20.Z", "Działalność w zakresie nagrań dźwiękowych i muzycznych"),
    ("PKD 60.10.Z", "Nadawanie programów radiofonicznych"),
    (
        "PKD 60.20.Z",
        "Nadawanie programów telewizyjnych ogólnodostępnych i abonamentowych",
    ),
    ("PKD 61.10.Z", "Działalność w zakresie telekomunikacji przewodowej"),
    (
        "PKD 61.20.Z",
        "Działalność w zakresie telekomunikacji bezprzewodowej, z wyłączeniem telekomunikacji satelitarnej",
    ),
    ("PKD 61.30.Z", "Działalność w zakresie telekomunikacji satelitarnej"),
    ("PKD 61.90.Z", "Działalność w zakresie pozostałej telekomunikacji"),
    ("PKD 62.01.Z", "Działalność związana z oprogramowaniem"),
    ("PKD 62.02.Z", "Działalność związana z doradztwem w zakresie informatyki"),
    ("PKD 62.03.Z", "Działalność związana z zarządzaniem urządzeniami informatycznymi"),
    (
        "PKD 62.09.Z",
        "Pozostała działalność usługowa w zakresie technologii informatycznych i komputerowych",
    ),
    (
        "PKD 63.11.Z",
        "Przetwarzanie danych; zarządzanie stronami internetowymi (hosting) i podobna działalność",
    ),
    ("PKD 63.12.Z", "Działalność portali internetowych"),
    ("PKD 63.91.Z", "Działalność agencji informacyjnych"),
    (
        "PKD 63.99.Z",
        "Pozostała działalność usługowa w zakresie informacji, gdzie indziej niesklasyfikowana",
    ),
    ("PKD 64.11.Z", "Działalność banku centralnego"),
    ("PKD 64.19.Z", "Pozostałe pośrednictwo pieniężne"),
    ("PKD 64.20.Z", "Działalność holdingów finansowych"),
    (
        "PKD 64.30.Z",
        "Działalność trustów, funduszów i podobnych instytucji finansowych",
    ),
    ("PKD 64.91.Z", "Leasing finansowy"),
    ("PKD 64.92.Z", "Pozostałe formy udzielania kredytów"),
    (
        "PKD 64.99.Z",
        "Pozostała finansowa działalność usługowa, gdzie indziej niesklasyfikowana, z wyłączeniem ubezpieczeń i funduszów emerytalnych",
    ),
    ("PKD 65.11.Z", "Ubezpieczenia na życie"),
    ("PKD 65.12.Z", "Pozostałe ubezpieczenia osobowe oraz ubezpieczenia majątkowe"),
    ("PKD 65.20.Z", "Reasekuracja"),
    ("PKD 65.30.Z", "Fundusze emerytalne"),
    ("PKD 66.11.Z", "Zarządzanie rynkami finansowymi"),
    (
        "PKD 66.12.Z",
        "Działalność maklerska związana z rynkiem papierów wartościowych i towarów giełdowych",
    ),
    (
        "PKD 66.19.Z",
        "Pozostała działalność wspomagająca usługi finansowe, z wyłączeniem ubezpieczeń i funduszów emerytalnych",
    ),
    (
        "PKD 66.21.Z",
        "Działalność związana z oceną ryzyka i szacowaniem poniesionych strat",
    ),
    ("PKD 66.22.Z", "Działalność agentów i brokerów ubezpieczeniowych"),
    (
        "PKD 66.29.Z",
        "Pozostała działalność wspomagająca ubezpieczenia i fundusze emerytalne",
    ),
    ("PKD 66.30.Z", "Działalność związana z zarządzaniem funduszami"),
    ("PKD 68.10.Z", "Kupno i sprzedaż nieruchomości na własny rachunek"),
    (
        "PKD 68.20.Z",
        "Wynajem i zarządzanie nieruchomościami własnymi lub dzierżawionymi",
    ),
    ("PKD 68.31.Z", "Pośrednictwo w obrocie nieruchomościami"),
    ("PKD 68.32.Z", "Zarządzanie nieruchomościami wykonywane na zlecenie"),
    ("PKD 69.10.Z", "Działalność prawnicza"),
    ("PKD 69.20.Z", "Działalność rachunkowo-księgowa; doradztwo podatkowe"),
    (
        "PKD 70.10.Z",
        "Działalność firm centralnych (head offices) i holdingów, z wyłączeniem holdingów finansowych",
    ),
    ("PKD 70.21.Z", "Stosunki międzyludzkie (public relations) i komunikacja"),
    (
        "PKD 70.22.Z",
        "Pozostałe doradztwo w zakresie prowadzenia działalności gospodarczej i zarządzania",
    ),
    ("PKD 71.11.Z", "Działalność w zakresie architektury"),
    (
        "PKD 71.12.Z",
        "Działalność w zakresie inżynierii i związane z nią doradztwo techniczne",
    ),
    ("PKD 71.20.A", "Badania i analizy związane z jakością żywności"),
    ("PKD 71.20.B", "Pozostałe badania i analizy techniczne"),
    ("PKD 72.11.Z", "Badania naukowe i prace rozwojowe w dziedzinie biotechnologii"),
    (
        "PKD 72.19.Z",
        "Badania naukowe i prace rozwojowe w dziedzinie pozostałych nauk przyrodniczych i technicznych",
    ),
    (
        "PKD 72.20.Z",
        "Badania naukowe i prace rozwojowe w dziedzinie nauk społecznych i humanistycznych",
    ),
    ("PKD 73.11.Z", "Działalność agencji reklamowych"),
    (
        "PKD 73.12.A",
        "Pośrednictwo w sprzedaży czasu i miejsca na cele reklamowe w radio i telewizji",
    ),
    (
        "PKD 73.12.B",
        "Pośrednictwo w sprzedaży miejsca na cele reklamowe w mediach drukowanych",
    ),
    (
        "PKD 73.12.C",
        "Pośrednictwo w sprzedaży miejsca na cele reklamowe w mediach elektronicznych (Internet)",
    ),
    (
        "PKD 73.12.D",
        "Pośrednictwo w sprzedaży miejsca na cele reklamowe w pozostałych mediach",
    ),
    ("PKD 73.20.Z", "Badanie rynku i opinii publicznej"),
    ("PKD 74.10.Z", "Działalność w zakresie specjalistycznego projektowania"),
    ("PKD 74.20.Z", "Działalność fotograficzna"),
    ("PKD 74.30.Z", "Działalność związana z tłumaczeniami"),
    (
        "PKD 74.90.Z",
        "Pozostała działalność profesjonalna, naukowa i techniczna, gdzie indziej niesklasyfikowana",
    ),
    ("PKD 75.00.Z", "DZIAŁALNOŚĆ WETERYNARYJNA"),
    ("PKD 77.11.Z", "Wynajem i dzierżawa samochodów osobowych i furgonetek"),
    (
        "PKD 77.12.Z",
        "Wynajem i dzierżawa pozostałych pojazdów samochodowych, z wyłączeniem motocykli",
    ),
    ("PKD 77.21.Z", "Wypożyczanie i dzierżawa sprzętu rekreacyjnego i sportowego"),
    ("PKD 77.22.Z", "Wypożyczanie kaset wideo, płyt CD, DVD itp."),
    (
        "PKD 77.29.Z",
        "Wypożyczanie i dzierżawa pozostałych artykułów użytku osobistego i domowego",
    ),
    ("PKD 77.31.Z", "Wynajem i dzierżawa maszyn i urządzeń rolniczych"),
    ("PKD 77.32.Z", "Wynajem i dzierżawa maszyn i urządzeń budowlanych"),
    (
        "PKD 77.33.Z",
        "Wynajem i dzierżawa maszyn i urządzeń biurowych, włączając komputery",
    ),
    ("PKD 77.34.Z", "Wynajem i dzierżawa środków transportu wodnego"),
    ("PKD 77.35.Z", "Wynajem i dzierżawa środków transportu lotniczego"),
    (
        "PKD 77.39.Z",
        "Wynajem i dzierżawa pozostałych maszyn, urządzeń oraz dóbr materialnych, gdzie indziej niesklasyfikowane",
    ),
    (
        "PKD 77.40.Z",
        "Dzierżawa własności intelektualnej i podobnych produktów, z wyłączeniem prac chronionych prawem autorskim",
    ),
    (
        "PKD 78.10.Z",
        "Działalność związana z wyszukiwaniem miejsc pracy i pozyskiwaniem pracowników",
    ),
    ("PKD 78.20.Z", "Działalność agencji pracy tymczasowej"),
    ("PKD 78.30.Z", "Pozostała działalność związana z udostępnianiem pracowników"),
    ("PKD 79.11.A", "Działalność agentów turystycznych"),
    ("PKD 79.11.B", "Działalność pośredników turystycznych"),
    ("PKD 79.12.Z", "Działalność organizatorów turystyki"),
    ("PKD 79.90.A", "Działalność pilotów wycieczek i przewodników turystycznych"),
    ("PKD 79.90.B", "Działalność w zakresie informacji turystycznej"),
    (
        "PKD 79.90.C",
        "Pozostała działalność usługowa w zakresie rezerwacji, gdzie indziej niesklasyfikowana",
    ),
    (
        "PKD 80.10.Z",
        "Działalność ochroniarska, z wyłączeniem obsługi systemów bezpieczeństwa",
    ),
    (
        "PKD 80.20.Z",
        "Działalność ochroniarska w zakresie obsługi systemów bezpieczeństwa",
    ),
    ("PKD 80.30.Z", "Działalność detektywistyczna"),
    (
        "PKD 81.10.Z",
        "Działalność pomocnicza związana z utrzymaniem porządku w budynkach",
    ),
    ("PKD 81.21.Z", "Niespecjalistyczne sprzątanie budynków i obiektów przemysłowych"),
    ("PKD 81.22.Z", "Specjalistyczne sprzątanie budynków i obiektów przemysłowych"),
    ("PKD 81.29.Z", "Pozostałe sprzątanie"),
    (
        "PKD 81.30.Z",
        "Działalność usługowa związana z zagospodarowaniem terenów zieleni",
    ),
    ("PKD 82.11.Z", "Działalność usługowa związana z administracyjną obsługą biura"),
    (
        "PKD 82.19.Z",
        "Wykonywanie fotokopii, przygotowywanie dokumentów i pozostała specjalistyczna działalność wspomagająca prowadzenie biura",
    ),
    ("PKD 82.20.Z", "Działalność centrów telefonicznych (call center)"),
    ("PKD 82.30.Z", "Działalność związana z organizacją targów, wystaw i kongresów"),
    ("PKD 82.91.Z", "Działalność świadczona przez agencje inkasa i biura kredytowe"),
    ("PKD 82.92.Z", "Działalność związana z pakowaniem"),
    (
        "PKD 82.99.Z",
        "Pozostała działalność wspomagająca prowadzenie działalności gospodarczej, gdzie indziej niesklasyfikowana",
    ),
    ("PKD 84.11.Z", "Kierowanie podstawowymi rodzajami działalności publicznej"),
    (
        "PKD 84.12.Z",
        "Kierowanie w zakresie działalności związanej z ochroną zdrowia, edukacją, kulturą oraz pozostałymi usługami społecznymi, z wyłączeniem zabezpieczeń społecznych",
    ),
    ("PKD 84.13.Z", "Kierowanie w zakresie efektywności gospodarowania"),
    ("PKD 84.21.Z", "Sprawy zagraniczne"),
    ("PKD 84.22.Z", "Obrona narodowa"),
    ("PKD 84.23.Z", "Wymiar sprawiedliwości"),
    ("PKD 84.24.Z", "Bezpieczeństwo państwa, porządek i bezpieczeństwo publiczne"),
    ("PKD 84.25.Z", "Ochrona przeciwpożarowa"),
    ("PKD 84.30.Z", "Obowiązkowe zabezpieczenia społeczne"),
    ("PKD 85.10.Z", "Wychowanie przedszkolne"),
    ("PKD 85.20.Z", "Szkoły podstawowe"),
    ("PKD 85.31.A", "Gimnazja"),
    ("PKD 85.31.B", "Licea ogólnokształcące"),
    ("PKD 85.31.C", "Licea profilowane"),
    ("PKD 85.32.A", "Technika"),
    ("PKD 85.32.B", "Zasadnicze szkoły zawodowe"),
    ("PKD 85.32.C", "Szkoły specjalne przysposabiające do pracy"),
    ("PKD 85.41.Z", "Szkoły policealne"),
    (
        "PKD 85.42.A",
        "Zakłady kształcenia nauczycieli i kolegia pracowników służb społecznych",
    ),
    ("PKD 85.42.B", "Szkoły wyższe"),
    (
        "PKD 85.51.Z",
        "Pozaszkolne formy edukacji sportowej oraz zajęć sportowych i rekreacyjnych",
    ),
    ("PKD 85.52.Z", "Pozaszkolne formy edukacji artystycznej"),
    ("PKD 85.53.Z", "Pozaszkolne formy edukacji z zakresu nauki jazdy i pilotażu"),
    ("PKD 85.59.A", "Nauka języków obcych"),
    (
        "PKD 85.59.B",
        "Pozostałe pozaszkolne formy edukacji, gdzie indziej niesklasyfikowane",
    ),
    ("PKD 85.60.Z", "Działalność wspomagająca edukację"),
    ("PKD 86.10.Z", "Działalność szpitali"),
    ("PKD 86.21.Z", "Praktyka lekarska ogólna"),
    ("PKD 86.22.Z", "Praktyka lekarska specjalistyczna"),
    ("PKD 86.23.Z", "Praktyka lekarska dentystyczna"),
    ("PKD 86.90.A", "Działalność fizjoterapeutyczna"),
    ("PKD 86.90.B", "Działalność pogotowia ratunkowego"),
    ("PKD 86.90.C", "Praktyka pielęgniarek i położnych"),
    ("PKD 86.90.D", "Działalność paramedyczna"),
    (
        "PKD 86.90.E",
        "Pozostała działalność w zakresie opieki zdrowotnej, gdzie indziej niesklasyfikowana",
    ),
    (
        "PKD 87.10.Z",
        "Pomoc społeczna z zakwaterowaniem zapewniająca opiekę pielęgniarską",
    ),
    (
        "PKD 87.20.Z",
        "Pomoc społeczna z zakwaterowaniem dla osób z zaburzeniami psychicznymi",
    ),
    (
        "PKD 87.30.Z",
        "Pomoc społeczna z zakwaterowaniem dla osób w podeszłym wieku i osób niepełnosprawnych",
    ),
    ("PKD 87.90.Z", "Pozostała pomoc społeczna z zakwaterowaniem"),
    (
        "PKD 88.10.Z",
        "Pomoc społeczna bez zakwaterowania dla osób w podeszłym wieku i osób niepełnosprawnych",
    ),
    ("PKD 88.91.Z", "Opieka dzienna nad dziećmi"),
    (
        "PKD 88.99.Z",
        "Pozostała pomoc społeczna bez zakwaterowania, gdzie indziej niesklasyfikowana",
    ),
    ("PKD 90.01.Z", "Działalność związana z wystawianiem przedstawień artystycznych"),
    ("PKD 90.02.Z", "Działalność wspomagająca wystawianie przedstawień artystycznych"),
    ("PKD 90.03.Z", "Artystyczna i literacka działalność twórcza"),
    ("PKD 90.04.Z", "Działalność obiektów kulturalnych"),
    ("PKD 91.01.A", "Działalność bibliotek"),
    ("PKD 91.01.B", "Działalność archiwów"),
    ("PKD 91.02.Z", "Działalność muzeów"),
    (
        "PKD 91.03.Z",
        "Działalność historycznych miejsc i budynków oraz podobnych atrakcji turystycznych",
    ),
    (
        "PKD 91.04.Z",
        "Działalność ogrodów botanicznych i zoologicznych oraz obszarów i obiektów ochrony przyrody",
    ),
    ("PKD 92.00.Z", "DZIAŁALNOŚĆ ZWIĄZANA Z GRAMI LOSOWYMI I ZAKŁADAMI WZAJEMNYMI"),
    ("PKD 93.11.Z", "Działalność obiektów sportowych"),
    ("PKD 93.12.Z", "Działalność klubów sportowych"),
    ("PKD 93.13.Z", "Działalność obiektów służących poprawie kondycji fizycznej"),
    ("PKD 93.19.Z", "Pozostała działalność związana ze sportem"),
    ("PKD 93.21.Z", "Działalność wesołych miasteczek i parków rozrywki"),
    ("PKD 93.29.Z", "Pozostała działalność rozrywkowa i rekreacyjna"),
    ("PKD 94.11.Z", "Działalność organizacji komercyjnych i pracodawców"),
    ("PKD 94.12.Z", "Działalność organizacji profesjonalnych"),
    ("PKD 94.20.Z", "Działalność związków zawodowych"),
    ("PKD 94.91.Z", "Działalność organizacji religijnych"),
    ("PKD 94.92.Z", "Działalność organizacji politycznych"),
    (
        "PKD 94.99.Z",
        "Działalność pozostałych organizacji członkowskich, gdzie indziej niesklasyfikowana",
    ),
    ("PKD 95.11.Z", "Naprawa i konserwacja komputerów i urządzeń peryferyjnych"),
    ("PKD 95.12.Z", "Naprawa i konserwacja sprzętu (tele)komunikacyjnego"),
    (
        "PKD 95.21.Z",
        "Naprawa i konserwacja elektronicznego sprzętu powszechnego użytku",
    ),
    (
        "PKD 95.22.Z",
        "Naprawa i konserwacja urządzeń gospodarstwa domowego oraz sprzętu użytku domowego i ogrodniczego",
    ),
    ("PKD 95.23.Z", "Naprawa obuwia i wyrobów skórzanych"),
    ("PKD 95.24.Z", "Naprawa i konserwacja mebli i wyposażenia domowego"),
    ("PKD 95.25.Z", "Naprawa zegarów, zegarków oraz biżuterii"),
    ("PKD 95.29.Z", "Naprawa pozostałych artykułów użytku osobistego i domowego"),
    ("PKD 96.01.Z", "Pranie i czyszczenie wyrobów włókienniczych i futrzarskich"),
    ("PKD 96.02.Z", "Fryzjerstwo i pozostałe zabiegi kosmetyczne"),
    ("PKD 96.03.Z", "Pogrzeby i działalność pokrewna"),
    ("PKD 96.04.Z", "Działalność usługowa związana z poprawą kondycji fizycznej"),
    ("PKD 96.09.Z", "Pozostała działalność usługowa, gdzie indziej niesklasyfikowana"),
    ("PKD 97.00.Z", "GOSPODARSTWA DOMOWE ZATRUDNIAJĄCE PRACOWNIKÓW"),
    ("PKD 98.10.Z", "Gospodarstwa domowe produkujące wyroby na własne potrzeby"),
    ("PKD 98.20.Z", "Gospodarstwa domowe świadczące usługi na własne potrzeby"),
    ("PKD 99.00.Z", "ORGANIZACJE I ZESPOŁY EKSTERYTORIALNE"),
]
