# Generated by Django 3.0.10 on 2020-10-22 18:38

from django.db import migrations
import supplierapi.apps.myAuth.models


class Migration(migrations.Migration):

    dependencies = [
        ('myAuth', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', supplierapi.apps.myAuth.models.UserManager()),
            ],
        ),
    ]
